src/App.vue, src/components/Projects/ListProject.vue, src/components/Users/CreateUser.vue, src/components/Users/HomePage.vue, src/components/Utils/About.vue, src/components/Utils/Footer.vue, src/components/Utils/Navbar.vue, src/router/index.js
Refatoração dos links e rotas do projeto para respeitar a arquitetura Single Page App do Vue
=> Issue 26 fix routes

LICENSE
=> [ADD] license

.dockerignore, .enlintrc.yml, .eslintignore, .travis.yml, Dockerfile.dev, Dockerfile.prod, Dockerfile.test, docker-compose.dev.yml, docker-compose.test.yml, express-prod-server.js, index.html, package-lock.json, package.json, src/components/Modals/modalRegister.vue, src/components/Observatorio/modalDeleteObservatorio.vue, src/components/Users/modalRegister.vue, src/components/Utils/Navbar.vue, src/main.js, start-prod.sh, test/unit/karma.conf.js, test/unit/specs/HelloWorld.spec.js
fixes this [issue](https://github.com/fga-gpp-mds/2018.1-TropicalHazards-BI/issues/129)
=> Issue 129 continous delivery

.travis.yml, index.html, src/components/Authentication/Login.vue, src/components/Authentication/Register.vue, src/components/Modals/modal.vue, src/components/Modals/modalDeleteProject.vue, src/components/Modals/modalEditUser.vue, src/components/Modals/modalNewProject.vue, src/components/Modals/modalRegister.vue, src/components/Observatorio/ObservatorioDetail.vue, src/components/Projects/CreateProject.vue, src/components/Projects/EditProject.vue, src/components/Projects/ListProject.vue, src/components/Projects/ProjectDetail.vue, src/components/Projects/modalDeleteProject.vue, src/components/Projects/modalNewProject.vue, src/components/Users/CreateUser.vue, src/components/Users/DeleteUser.vue, src/components/Users/EditUser.vue, src/components/Users/HomePage.vue, src/components/Users/modal.vue, src/components/Users/modalEditUser.vue, src/components/Users/modalRegister.vue, src/components/Utils/Navbar.vue, src/components/Utils/SecondNavBar.vue, src/components/Utils/SideBar.vue, src/main.js
=> Issue 41 about text

src/components/Observatorio/createObservatorio.vue, src/components/Projects/ProjectDetail.vue, src/router/index.js
=> [ADD] add create observatory

src/App.vue
=> [UPDATE] update animations to transitions components

src/components/Observatorio/ObservatorioDetail.vue, src/components/Observatorio/editObseravatorio.vue, src/components/Observatorio/editObservatorio.vue, src/components/Projects/ProjectDetail.vue, src/components/Users/HomePage.vue, src/router/index.js
=> Issue 48 delete dashboard

src/components/Observatorio/editObseravatorio.vue, src/components/Observatorio/editObservatorio.vue, src/components/Projects/ProjectDetail.vue, src/components/Users/HomePage.vue, src/router/index.js
Agora é possivel editar o nome do observatório do projeto.
=> Issue 50 edit dashboard

package-lock.json, package.json, src/components/Files/ImportCsv.vue, src/components/Projects/ProjectDetail.vue, src/main.js
- Instalação do plugin vue-js-modal
- Criação da modal para inserção de csv
- Validação na modal
=> Issue 47 insert csv

src/components/Utils/Footer.vue
- Atualiza o conteúdo do footer
=> Issue 64 footer content

package-lock.json, package.json, src/components/Files/DefineData.vue, src/components/Files/FilterCsv.vue, src/components/Files/ImportCsv.vue, src/components/Files/SendData.vue, src/components/Projects/ProjectDetail.vue
- Adiciona componentes para filtro de dados
=> Issue 68 csv data filter

src/components/Users/HomePage.vue
Um campo de busca foi adicionado a HomePage para filtrar os projetos pela tag.
=> Issue 70 filter projects by tag

src/components/Files/DefineData.vue, src/components/Files/SendData.vue
=> Issue 68 csv filter data type fix

.travis.yml, package-lock.json, package.json
=> semantic-release configurations

.eslintrc.js, src/components/Observatorio/ObservatorioDetail.vue, src/components/Observatorio/createObservatorio.vue, src/components/Observatorio/modalDeleteObservatorio.vue, src/components/Projects/CreateProject.vue, src/components/Projects/CreateTag.vue, src/components/Users/DeleteUser.vue, src/components/Users/EditUser.vue, src/components/Users/HomePage.vue, src/components/Utils/Navbar.vue
=> Issue 90 resolve errors de jquery

.travis.yml, semantic-release.sh, travis-deploy.sh
Corrige processo do travis no rancher.
=> [HOTFIX] fix travis deploy pipeline to rancher

src/components/Files/DefineData.vue, src/components/Files/FilterCsv.vue, src/components/Files/SendData.vue
Adiciona interface para definição de dados
=> Issue 56 data def interface

Dockerfile, docker-compose.test.yml, docker-compose.yml, package-lock.json, package.json, semantic-release.sh, src/main.js, start.sh
Altera o script da aplicação para rodar o npm install e tira o comando do Dockerfile pois ao mapear o volume no docker compose a pasta contendo o node_modules era sobrescrita. Adiciona sentry para monitorar erros e exceções da aplicação.
=> Issue 104 sentry setup and docker volume fix

README.md, config/prod.env.js
=> fix(deploy): changes homolog address

README.md
=> [UPDATE] removes codacy badge

src/components/Auth/Auth.vue, src/components/Landing/LandingPage.vue
=> Fixes footer display on pages

src/store/Projects/Project.js
- Adiciona métodos para coletar os ids dos fields do metabase
- Adiciona ao vuex state currentProject e currentProjectFields
=> Issue 106 collect metabase data

src/components/Auth/LoginForm.vue, src/components/Auth/middleware.js, src/components/Modals/modalLogin.vue, src/components/Utils/SideBar.vue, src/router/index.js, src/store/Authentication/auth.js
=> Issue 117 navigation guard

semantic-release.sh
=> [FIX] semantic release

src/components/Landing/Header.vue, src/components/Landing/LandingPage.vue, src/components/Projects/MyProjects.vue, src/store/Authentication/auth.js, src/store/Projects/Project.js
Agora são mostrados apenas os projetos do usuário relacionado
=>  [UPDATE] update page my projects to see only currentUser projects

src/components/Projects/CreateProject.vue, src/components/Projects/MyProjects.vue, src/components/Users/HomePage.vue, src/router/index.js
- Implementa nested routes a HomePage, dessa forma apenas o conteúdo necessário é recarregado.
=> Issue 140 nested routes

src/components/Landing/Navbar.vue
opção de logout e boas vindas com o nome o usuario se ele estiver logado
=> solves #150

src/components/Landing/Navbar.vue, src/components/Projects/MyProjects.vue, src/components/Utils/SideBar.vue
=> [FIX] fix some bugs describle on issue

src/App.vue, src/components/Files/ContainerImport.vue, src/components/Files/DefineBool.vue, src/components/Files/Filter.vue, src/components/Files/FilterCsv.vue, src/components/Files/ImportCsv.vue, src/components/Files/SendData.vue, src/components/Projects/MyProjects.vue, src/components/Projects/ProjectDetail.vue, src/components/Projects/ProjectsList.vue, src/router/index.js
=> Issue 146 refact import data

src/components/Dashboards/DashboardDetail.vue, src/components/Landing/Navbar.vue, src/components/Users/HomePage.vue, src/router/index.js
[FIX] route to dashboard list component
quando a visualização for mobile vai ter um btn junto à navbar para mudar a visibilidade da sidebar
=> Responsive btn to sidebar
